import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import ThemeInitializer from '@components/system/ThemeInitializer';
import { Toaster } from 'react-hot-toast';
import SideBarWrapper from '@components/layout/SideBarWrapper';
import { InitUserStore } from '@stores/userStore';
import RightPanel from '@components/layout/RightPanel';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex h-screen">
          <SideBarWrapper />
          <div className="flex flex-1 overflow-hidden">
            <main className="flex-1 overflow-auto">{children}</main>
            <RightPanel />
          </div>
        </div>
        <InitUserStore />
        <ThemeInitializer />
        <Toaster position="top-center" reverseOrder={false} />
      </body>
    </html>
  );
}
